name: Deploy

on:
  push:
    branches:
      - 'project_5'
    paths:
      - 'front-end/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "connecthedots" #Must be unique in Heroku
          heroku_email: "tgloverxi0819@gmail.com"
          appdir: "front-end" # <- This will point to the api folder in your project